//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IdCita { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string IdEspecialidad { get; set; }
        public Nullable<int> Identificacion { get; set; }
    
        public virtual Especialidad Especialidad { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
